//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestifyTF2.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RequestifyTF2.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find usable device. Make sure that you have VB-Audio or Virtual Audio Cable installed and enabled in device manager!.
        /// </summary>
        internal static string CORE_CANNOT_FIND_DEVICES {
            get {
                return ResourceManager.GetString("CORE_CANNOT_FIND_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant load plugin: .
        /// </summary>
        internal static string CORE_CANT_LOAD_PLUGIN {
            get {
                return ResourceManager.GetString("CORE_CANT_LOAD_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find directory .
        /// </summary>
        internal static string CORE_ERROR_CANT_FIND_DIR {
            get {
                return ResourceManager.GetString("CORE_ERROR_CANT_FIND_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove lines from console.log. The game is probably running. Please close the game before starting this program.
        /// </summary>
        internal static string CORE_ERROR_CANT_PREPARE_CONSOLE_LOG {
            get {
                return ResourceManager.GetString("CORE_ERROR_CANT_PREPARE_CONSOLE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while setting {0} as default input device
        ///{1}.
        /// </summary>
        internal static string CORE_ERROR_WHILE_SETTING_INPUT {
            get {
                return ResourceManager.GetString("CORE_ERROR_WHILE_SETTING_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found. Please fix errors before using this program..
        /// </summary>
        internal static string CORE_ERRORS_FOUND_CLOSE_PROGRAM {
            get {
                return ResourceManager.GetString("CORE_ERRORS_FOUND_CLOSE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} executed {1}.
        /// </summary>
        internal static string CORE_EXECUTED_COMMAND {
            get {
                return ResourceManager.GetString("CORE_EXECUTED_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plugin: .
        /// </summary>
        internal static string CORE_INVALID_PLUGIN {
            get {
                return ResourceManager.GetString("CORE_INVALID_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plugin: {0}
        /// Plugin has more than 1 interface.
        /// </summary>
        internal static string CORE_INVALID_PLUGIN_MORE_THAN_ONE_INTERFACE {
            get {
                return ResourceManager.GetString("CORE_INVALID_PLUGIN_MORE_THAN_ONE_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked {0} OnLoad method! .
        /// </summary>
        internal static string CORE_INVOKED_ONLOAD_METHOD {
            get {
                return ResourceManager.GetString("CORE_INVOKED_ONLOAD_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0}.
        /// </summary>
        internal static string CORE_LOADED_PLUGIN {
            get {
                return ResourceManager.GetString("CORE_LOADED_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching autoexec.cfg.
        /// </summary>
        internal static string CORE_PATCHING_AUTOEXEC {
            get {
                return ResourceManager.GetString("CORE_PATCHING_AUTOEXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing {0} from {1}.
        /// </summary>
        internal static string CORE_PLAYING_TITLE_FROM {
            get {
                return ResourceManager.GetString("CORE_PLAYING_TITLE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0} from {1}.
        /// </summary>
        internal static string CORE_PLUGIN_LOADING_FROM {
            get {
                return ResourceManager.GetString("CORE_PLUGIN_LOADING_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for usable devices....
        /// </summary>
        internal static string CORE_SEARCHING_FOR_DEVICES {
            get {
                return ResourceManager.GetString("CORE_SEARCHING_FOR_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set game directory.
        /// </summary>
        internal static string CORE_SET_DIRECTORY {
            get {
                return ResourceManager.GetString("CORE_SET_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started LogReader Thread!.
        /// </summary>
        internal static string CORE_STARTED_LOGREADER_THREAD {
            get {
                return ResourceManager.GetString("CORE_STARTED_LOGREADER_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Player Thread!.
        /// </summary>
        internal static string CORE_STARTED_PLAYER_THREAD {
            get {
                return ResourceManager.GetString("CORE_STARTED_PLAYER_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used {0} as output device and {1} as input device.
        /// </summary>
        internal static string CORE_USED_DEVICES {
            get {
                return ResourceManager.GetString("CORE_USED_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was blacklisted to execute {1}.
        /// </summary>
        internal static string CORE_USER_BLACKLISTED_FOR_EXECUTING {
            get {
                return ResourceManager.GetString("CORE_USER_BLACKLISTED_FOR_EXECUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invoked {1}.
        /// </summary>
        internal static string CORE_USER_INVOKED {
            get {
                return ResourceManager.GetString("CORE_USER_INVOKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked {0} OnLoad method! .
        /// </summary>
        internal static string INVOKED_ONLOAD_METHOD {
            get {
                return ResourceManager.GetString("INVOKED_ONLOAD_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *DEAD*.
        /// </summary>
        internal static string TF_CHAT_DEAD {
            get {
                return ResourceManager.GetString("TF_CHAT_DEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Spectator).
        /// </summary>
        internal static string TF_CHAT_SPECTATOR {
            get {
                return ResourceManager.GetString("TF_CHAT_SPECTATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (TEAM).
        /// </summary>
        internal static string TF_CHAT_TEAM {
            get {
                return ResourceManager.GetString("TF_CHAT_TEAM", resourceCulture);
            }
        }
    }
}
